apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-sa
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "demo-app"
    vault.hashicorp.com/agent-inject-secret-config.txt: "secret/data/demo-app"
spec:
  serviceAccountName: demo-app-sa
  containers:
    - name: demo
      image: busybox
      command: ["sleep", "3600"]

