---
- name: Setup k3s master node
  hosts: masters
  become: yes
  tasks:
    - name: Install k3s server
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

- name: Get k3s token from master
  hosts: masters
  gather_facts: no
  tasks:
    - name: Read k3s node token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Set token fact
      set_fact:
        k3s_token: "{{ node_token.stdout }}"

  run_once: true

- name: Setup k3s worker nodes
  hosts: workers
  become: yes
  vars:
    master_ip: "{{ hostvars[groups['masters'][0]].ansible_host }}"
    token: "{{ hostvars[groups['masters'][0]].k3s_token }}"
  tasks:
    - name: Install k3s agent
      shell: >
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ token }} sh -
      args:
        creates: /usr/local/bin/k3s
